#!/bin/sh

PATTERN="."
[ -z "$VIS_MENU" ] && VIS_MENU="slmenu"
[ -z "$VIS_MENU_ARGS" ] && VIS_MENU_ARGS="-b"

while [ $# -gt 0 ]; do
	case "$1" in
	-h|--help)
		echo "usage: $(basename $0) [-h] [-p prompt]"
		exit 0;
		;;
	-p)
		VIS_MENU_ARGS="$VIS_MENU_ARGS -p $2"
		shift
		shift
		;;
	*)
		break
		;;
	esac
done

if ! type "$VIS_MENU" >/dev/null 2>&1; then
	if [ ! -z "$DISPLAY" ] && type "dmenu" >/dev/null 2>&1; then
		VIS_MENU="dmenu"
	else
		echo "Neither slmenu nor dmenu found" >&2
		exit 1
	fi
fi

exec $VIS_MENU $VIS_MENU_ARGS
