#!/bin/sh

if [ ! -z "$DISPLAY" ]; then
	exec xsel -ob
elif type pbpaste >/dev/null 2>&1; then
	exec pbpaste
elif [ -c /dev/clipboard ]; then
	exec cat /dev/clipboard
else
	echo "System clipboard not supported" 1>&2
	exit 1
fi
