#!/bin/sh
set -e

PATTERN=""
COMPLETE_WORD=0
FIND_FILE_LIMIT=1000

while [ $# -gt 0 ]; do
	case "$1" in
	-h|--help)
		echo "usage: $(basename "$0") [-h] [--file|--word] [pattern]"
		exit 0;
		;;
	--file)
		shift
		;;
	--word)
		COMPLETE_WORD=1
		shift
		;;
	*)
		PATTERN="$1"
		break
		;;
	esac
done

if [ $COMPLETE_WORD = 1 ]; then
	tr -cs '[:alnum:]_' '\n' | grep "^$PATTERN." | sort -u
else
	find . ! -path '*/\.*' -a -path "./$PATTERN*" 2>/dev/null | head -n $FIND_FILE_LIMIT | cut -b 3- | sort
fi | vis-menu -b | sed "s/^$(printf "%s" "$PATTERN" | sed 's:/:\\/:g' )//" | tr -d '\n'
