#!/bin/sh
set -e

print_completion() { vis-menu -b | sed "s/^$1//" | tr -d '\n'; }
usage() { echo "usage: $(basename "$0") [--word|--file] [pattern]"; }

COMPLETE_WORD=0
FIND_FILE_LIMIT=1000

while [ $# -gt 0 ]; do
	case "$1" in
	-h|--help)
		usage 1>&2
		exit 0;
		;;
	--file)
		shift
		;;
	--word)
		COMPLETE_WORD=1
		shift
		;;
	*)
		break
		;;
	esac
done

if [ $COMPLETE_WORD = 1 ]; then
	tr -cs '[:alnum:]_' '\n' |
		grep "^$1." |
		sort -u |
		print_completion "$1"
else
	# glob quoting
	PATTERN=$(printf "%s" "$1" | sed 's|[\\?*[]]|\\&|g')

	find "$PATTERN"* \
		-name '.*' -prune \
		-o -print 2>/dev/null |
		head -n $FIND_FILE_LIMIT |
		sort |
		sed "s|^$(dirname $PATTERN.)/||" |
		print_completion "$(basename "$PATTERN")"
fi
