vis:map(vis.modes.NORMAL, "K", function()
	vis:feedkeys("iNormal Mode<Enter><Escape>")
end)
vis:map(vis.modes.INSERT, "K", function()
	vis:feedkeys("Insert Mode<Enter><Escape>")
end)
vis:map(vis.modes.VISUAL, "K", function()
	vis:feedkeys("<Escape>iVisual Mode<Enter><Escape>")
end)
vis:map(vis.modes.VISUAL_LINE, "K", function()
	vis:feedkeys("<Escape>iVisual Line Mode<Enter><Escape>")
end)
vis:map(vis.modes.REPLACE, "K", function()
	vis:feedkeys("Replace Mode<Enter><Escape>")
end)

vis:feedkeys("K")
vis:feedkeys("iK")
vis:feedkeys("vK")
vis:feedkeys("VK")
vis:feedkeys("RK")
vis:feedkeys("dd")

vis:command("w! basic_map.out")