vis:map(vis.MODE_NORMAL, "K", function()
	vis:feedkeys("aNormal Mode<Enter><vis-mode-normal>")
end)
vis:map(vis.MODE_INSERT, "K", function()
	vis:feedkeys("Insert Mode<Enter><vis-mode-normal>")
end)
vis:map(vis.MODE_VISUAL, "K", function()
	vis:feedkeys("<vis-mode-normal>aVisual Mode<Enter><vis-mode-normal>")
end)
vis:map(vis.MODE_VISUAL_LINE, "K", function()
	vis:feedkeys("<vis-mode-normal>aVisual Line Mode<Enter><vis-mode-normal>")
end)
vis:map(vis.MODE_REPLACE, "K", function()
	vis:feedkeys("Replace Mode<Enter><vis-mode-normal>")
end)

vis:feedkeys("K")
vis:feedkeys("iK")
vis:feedkeys("vK")
vis:feedkeys("VK")
vis:feedkeys("RK")

vis:command("w! basic_map.out")